import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'nav.login': 'Employee Login',
    'nav.dashboard': 'Dashboard',
    'nav.patients': 'Patients',
    'nav.appointments': 'Appointments',
    'nav.reports': 'Reports',
    'nav.signOut': 'Sign Out',
    
    // Hero Section
    'hero.title': 'Comprehensive Health Records for',
    'hero.titleHighlight': 'Women & Children',
    'hero.subtitle': 'Empowering communities through accessible healthcare monitoring, maternal wellness tracking, and child development support.',
    'hero.startMonitoring': 'Start Monitoring',
    'hero.learnMore': 'Learn More',
    'hero.patientsServed': 'Patients Served',
    'hero.successRate': 'Success Rate',
    'hero.careAvailable': 'Care Available',
    
    // Features
    'features.title': 'Why Choose SheCure?',
    'features.subtitle': 'Comprehensive healthcare solutions designed for women and children',
    'features.maternal.title': 'Maternal Health Monitoring',
    'features.maternal.desc': 'Track pregnancy progress, appointments, and health metrics for expecting mothers.',
    'features.child.title': 'Child Development Tracking',
    'features.child.desc': 'Monitor growth milestones, vaccination schedules, and pediatric care.',
    'features.health.title': 'Health Record Management',
    'features.health.desc': 'Secure digital health records accessible anytime, anywhere.',
    'features.community.title': 'Community Healthcare',
    'features.community.desc': 'Connect with local healthcare providers and NGO support networks.',
    'features.appointment.title': 'Appointment Scheduling',
    'features.appointment.desc': 'Easy booking and management of healthcare appointments.',
    'features.reports.title': 'Health Reports & Analytics',
    'features.reports.desc': 'Generate detailed health reports and track wellness trends.',
    
    // About Developers
    'about.title': 'About the Developers',
    'about.subtitle': 'Meet the passionate team behind SheCure',
    'about.ramya.name': 'Ramya Prabha B',
    'about.ramya.role': 'Lead Developer',
    'about.ramya.bio': 'Passionate healthcare technology developer with expertise in creating accessible digital solutions for maternal and child health initiatives.',
    'about.vaishnavi.name': 'Vaishnavi Soni',
    'about.vaishnavi.role': 'Frontend Developer',
    'about.vaishnavi.bio': 'Experienced in building user-friendly interfaces and implementing responsive designs for healthcare applications.',
    
    // Dashboard
    'dashboard.title': 'Health Dashboard',
    'dashboard.subtitle': 'Monitor health records and track patient wellness',
    'dashboard.totalPatients': 'Total Patients',
    'dashboard.healthyPregnancies': 'Healthy Pregnancies',
    'dashboard.childrenVaccinated': 'Children Monitored',
    'dashboard.activeCases': 'Active Cases',
    'dashboard.recentPatients': 'Recent Patients',
    'dashboard.healthMetrics': 'Health Metrics',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.addNewPatient': 'Add New Patient',
    'dashboard.scheduleAppointment': 'Schedule Appointment',
    'dashboard.generateReport': 'Generate Report',
    'dashboard.maternalHealth': 'Maternal Health',
    'dashboard.childWellness': 'Child Wellness',
    'dashboard.vaccinationRate': 'Vaccination Rate',
    'dashboard.patientDetails': 'Patient Details',
    'dashboard.viewMedicalHistory': 'View Medical History',
    'dashboard.updateRecords': 'Update Records',
    
    // Auth Page
    'auth.welcomeBack': 'Welcome Back',
    'auth.joinSheCure': 'Join SheCure',
    'auth.signInAccount': 'Sign in to your NGO employee account',
    'auth.createAccount': 'Create your NGO employee account',
    'auth.fullName': 'Full Name',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.dontHaveAccount': "Don't have an account? Sign up",
    'auth.alreadyHaveAccount': 'Already have an account? Sign in',
    'auth.backToHome': 'Back to Home',
    
    // Common Actions
    'common.viewDetails': 'View Details',
    'common.schedule': 'Schedule',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
     'common.edit': 'Edit',
     'common.delete': 'Delete',
     'common.add': 'Add',
     'common.update': 'Update',
     'common.export': 'Export Data',
     'common.filter': 'Filter',
     'common.search': 'Search',
     'common.download': 'Download',
     'common.monitor': 'Monitor',
     'common.call': 'Call',
     'common.emergencyAlert': 'Emergency Alert',
     'common.newAppointment': 'New Appointment',
     'common.calendarView': 'Calendar View',
     'common.generateReport': 'Generate Report',
     'common.scheduleReport': 'Schedule Report',
     
     // Patient Records
     'patients.title': 'Patient Records',
     'patients.subtitle': 'Manage and monitor all patient health records',
     'patients.searchPlaceholder': 'Search patients by name...',
     'patients.allPatients': 'All Patients',
     'patients.active': 'Active',
     'patients.critical': 'Critical',
     'patients.moreFilters': 'More Filters',
     'patients.noPatients': 'No patients found matching your criteria.',
     'patients.noData': 'No patients added yet. Click "Add Patient" to get started.',
     'patients.addPatient': 'Add Patient',
     'patients.priorityCases': 'Priority Cases',
     'patients.patientDetails': 'Patient Details',
     'patients.age': 'Age',
     'patients.condition': 'Condition',
     'patients.phone': 'Phone',
     'patients.address': 'Address',
     'patients.location': 'Location',
     'patients.status': 'Status',
     'patients.lastVisit': 'Last Visit',
     'patients.quickActions': 'Quick Actions',
     'patients.patientInfo': 'Patient Information',
     'patients.years': 'years',
     'patients.notProvided': 'Not provided',
     
     // Appointments
     'appointments.title': 'Appointments',
     'appointments.subtitle': 'Schedule and manage patient appointments',
     'appointments.todaySchedule': "Today's Schedule",
     'appointments.upcomingWeek': 'Upcoming This Week',
     'appointments.todaySummary': "Today's Summary",
     'appointments.totalAppointments': 'Total Appointments',
     'appointments.confirmed': 'Confirmed',
     'appointments.pending': 'Pending',
     'appointments.highPriority': 'High Priority',
     'appointments.patientName': 'Patient Name',
     'appointments.type': 'Type',
     'appointments.time': 'Time',
     'appointments.duration': 'Duration',
     'appointments.doctor': 'Doctor',
     'appointments.priority': 'Priority',
     'appointments.appointmentDetails': 'Appointment Details',
     'appointments.patientInfo': 'Patient Information',
     'appointments.editAppointment': 'Edit Appointment',
     'appointments.cancelAppointment': 'Cancel Appointment',
     'appointments.day': 'Day',
     'appointments.week': 'Week',
     'appointments.month': 'Month',
     'appointments.filterByStatus': 'Filter by Status',
     
     // Reports
     'reports.title': 'Health Reports',
     'reports.subtitle': 'Generated health analytics and performance reports',
     'reports.totalGenerated': 'Total Reports Generated',
     'reports.maternalCoverage': 'Maternal Health Coverage',
     'reports.childVaccination': 'Child Vaccination Rate',
     'reports.dataQuality': 'Data Quality Score',
     'reports.thisMonth': 'this month',
     'reports.fromTarget': 'from target',
     'reports.dataIntegrity': 'Excellent data integrity',
     'reports.allReports': 'All Reports',
     'reports.maternalHealth': 'Maternal Health',
     'reports.childHealth': 'Child Health',
     'reports.vaccination': 'Vaccination',
     'reports.period': 'Period',
     'reports.generated': 'Generated',
     'reports.keyMetrics': 'Key Metrics',
     'reports.customReport': 'Need a Custom Report?',
     'reports.customReportDesc': 'Generate specific reports based on your requirements with our advanced analytics engine.',
     'reports.createCustom': 'Create Custom Report',
     'reports.reportDetails': 'Report Details',
     'reports.summary': 'Summary',
     'reports.scheduleSuccess': 'Report Scheduled',
     'reports.scheduleDesc': 'Your report has been scheduled for weekly generation.',
     'reports.generateSuccess': 'Report Generated Successfully',
     'reports.generateDesc': 'Your health report has been generated and is ready for download.',
     'reports.downloadStart': 'Download Started',
     'reports.downloadDesc': 'is being downloaded.',
     'reports.exportSuccess': 'Export Successful',
     'reports.exportDesc': 'patient records exported successfully.',
     'reports.weekly': 'Weekly',
     'reports.monthly': 'Monthly',
     'reports.quarterly': 'Quarterly',
     'reports.yearly': 'Yearly',
     'reports.completed': 'Completed',
     'reports.processing': 'Processing',
     'reports.scheduleSimilar': 'Schedule Similar Report',
     
     // Critical Patients
     'critical.title': 'Critical Patients Alert',
     'critical.postpartumHypertension': 'Postpartum hypertension',
     'critical.highRiskPregnancy': 'High-risk pregnancy monitoring',
     
     // Emergency
     'emergency.title': 'Emergency Alert Activated',
     'emergency.description': 'Emergency services have been notified and medical assistance is being dispatched.',
     'emergency.eta': 'Medical team ETA: 10-15 minutes',
     'emergency.contact': 'Emergency contact: +91 108',
     'emergency.reference': 'Reference ID',
     'emergency.triggered': 'Emergency Alert Triggered',
     'emergency.response': 'Emergency services have been notified. Medical team will respond immediately.',
     
     // Form Labels
     'form.name': 'Name',
     'form.age': 'Age',
     'form.phone': 'Phone',
     'form.address': 'Address',
     'form.condition': 'Condition',
     'form.notes': 'Notes',
     
     // Footer
     'footer.mission': 'Our Mission',
     'footer.missionText': 'To provide accessible, comprehensive healthcare monitoring for women and children in underserved communities.',
     'footer.copyright': '© 2025 SheCure. Built with ❤️ for better healthcare.',
     'footer.tagline': 'Empowering women and children through accessible healthcare',
  },
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.about': 'हमारे बारे में',
    'nav.services': 'सेवाएं',
    'nav.contact': 'संपर्क',
    'nav.login': 'कर्मचारी लॉगिन',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.patients': 'मरीज़',
    'nav.appointments': 'अपॉइंटमेंट',
    'nav.reports': 'रिपोर्ट',
    'nav.signOut': 'साइन आउट',
    
    // Hero Section
    'hero.title': 'महिलाओं और बच्चों के लिए',
    'hero.titleHighlight': 'व्यापक स्वास्थ्य रिकॉर्ड',
    'hero.subtitle': 'सुलभ स्वास्थ्य निगरानी, मातृ कल्याण ट्रैकिंग, और बाल विकास सहायता के माध्यम से समुदायों को सशक्त बनाना।',
    'hero.startMonitoring': 'निगरानी शुरू करें',
    'hero.learnMore': 'और जानें',
    'hero.patientsServed': 'सेवा प्राप्त मरीज़',
    'hero.successRate': 'सफलता दर',
    'hero.careAvailable': 'देखभाल उपलब्ध',
    
    // Features
    'features.title': 'SheCure क्यों चुनें?',
    'features.subtitle': 'महिलाओं और बच्चों के लिए डिज़ाइन किए गए व्यापक स्वास्थ्य समाधान',
    'features.maternal.title': 'मातृ स्वास्थ्य निगरानी',
    'features.maternal.desc': 'गर्भवती माताओं के लिए गर्भावस्था की प्रगति, अपॉइंटमेंट और स्वास्थ्य मेट्रिक्स को ट्रैक करें।',
    'features.child.title': 'बाल विकास ट्रैकिंग',
    'features.child.desc': 'विकास मील के पत्थर, टीकाकरण कार्यक्रम और बाल चिकित्सा देखभाल की निगरानी करें।',
    'features.health.title': 'स्वास्थ्य रिकॉर्ड प्रबंधन',
    'features.health.desc': 'कभी भी, कहीं भी सुरक्षित डिजिटल स्वास्थ्य रिकॉर्ड एक्सेस करें।',
    'features.community.title': 'सामुदायिक स्वास्थ्य सेवा',
    'features.community.desc': 'स्थानीय स्वास्थ्य सेवा प्रदाताओं और NGO सहायता नेटवर्क से जुड़ें।',
    'features.appointment.title': 'अपॉइंटमेंट शेड्यूलिंग',
    'features.appointment.desc': 'स्वास्थ्य अपॉइंटमेंट की आसान बुकिंग और प्रबंधन।',
    'features.reports.title': 'स्वास्थ्य रिपोर्ट और विश्लेषण',
    'features.reports.desc': 'विस्तृत स्वास्थ्य रिपोर्ट तैयार करें और कल्याण रुझानों को ट्रैक करें।',
    
    // About Developers
    'about.title': 'डेवलपर्स के बारे में',
    'about.subtitle': 'SheCure के पीछे के उत्साही टीम से मिलें',
    'about.ramya.name': 'रम्या प्रभा बी',
    'about.ramya.role': 'मुख्य डेवलपर',
    'about.ramya.bio': 'मातृ और बाल स्वास्थ्य पहलों के लिए सुलभ डिजिटल समाधान बनाने में विशेषज्ञता रखने वाली स्वास्थ्य प्रौद्योगिकी डेवलपर।',
    'about.vaishnavi.name': 'वैष्णवी सोनी',
    'about.vaishnavi.role': 'फ्रंटएंड डेवलपर',
    'about.vaishnavi.bio': 'स्वास्थ्य एप्लिकेशन के लिए उपयोगकर्ता-अनुकूल इंटरफेस बनाने और रिस्पॉन्सिव डिज़ाइन लागू करने में अनुभवी।',
    
    // Dashboard
    'dashboard.title': 'स्वास्थ्य डैशबोर्ड',
    'dashboard.subtitle': 'स्वास्थ्य रिकॉर्ड की निगरानी करें और मरीज़ों के कल्याण को ट्रैक करें',
    'dashboard.totalPatients': 'कुल मरीज़',
    'dashboard.healthyPregnancies': 'स्वस्थ गर्भावस्था',
    'dashboard.childrenVaccinated': 'बच्चों की निगरानी',
    'dashboard.activeCases': 'सक्रिय मामले',
    'dashboard.recentPatients': 'हाल के मरीज़',
    'dashboard.healthMetrics': 'स्वास्थ्य मेट्रिक्स',
    'dashboard.quickActions': 'त्वरित कार्य',
    'dashboard.addNewPatient': 'नया मरीज़ जोड़ें',
    'dashboard.scheduleAppointment': 'अपॉइंटमेंट शेड्यूल करें',
    'dashboard.generateReport': 'रिपोर्ट जेनरेट करें',
    'dashboard.maternalHealth': 'मातृ स्वास्थ्य',
    'dashboard.childWellness': 'बाल कल्याण',
    'dashboard.vaccinationRate': 'टीकाकरण दर',
    'dashboard.patientDetails': 'मरीज़ विवरण',
    'dashboard.viewMedicalHistory': 'चिकित्सा इतिहास देखें',
    'dashboard.updateRecords': 'रिकॉर्ड अपडेट करें',
    
    // Auth Page
    'auth.welcomeBack': 'वापस स्वागत है',
    'auth.joinSheCure': 'SheCure में शामिल हों',
    'auth.signInAccount': 'अपने NGO कर्मचारी खाते में साइन इन करें',
    'auth.createAccount': 'अपना NGO कर्मचारी खाता बनाएं',
    'auth.fullName': 'पूरा नाम',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.signIn': 'साइन इन',
    'auth.signUp': 'साइन अप',
    'auth.dontHaveAccount': 'खाता नहीं है? साइन अप करें',
    'auth.alreadyHaveAccount': 'पहले से खाता है? साइन इन करें',
    'auth.backToHome': 'होम पर वापस जाएं',
    
    // Common Actions
    'common.viewDetails': 'विवरण देखें',
    'common.schedule': 'शेड्यूल',
    'common.close': 'बंद करें',
    'common.save': 'सेव करें',
    'common.cancel': 'रद्द करें',
     'common.edit': 'संपादित करें',
     'common.delete': 'हटाएं',
     'common.add': 'जोड़ें',
     'common.update': 'अपडेट करें',
     'common.export': 'डेटा निर्यात करें',
     'common.filter': 'फिल्टर',
     'common.search': 'खोजें',
     'common.download': 'डाउनलोड',
     'common.monitor': 'निगरानी',
     'common.call': 'कॉल',
     'common.emergencyAlert': 'आपातकालीन अलर्ट',
     'common.newAppointment': 'नई अपॉइंटमेंट',
     'common.calendarView': 'कैलेंडर दृश्य',
     'common.generateReport': 'रिपोर्ट जेनरेट करें',
     'common.scheduleReport': 'रिपोर्ट शेड्यूल करें',
     
     // Patient Records
     'patients.title': 'मरीज़ रिकॉर्ड',
     'patients.subtitle': 'सभी मरीज़ों के स्वास्थ्य रिकॉर्ड का प्रबंधन और निगरानी करें',
     'patients.searchPlaceholder': 'नाम से मरीज़ खोजें...',
     'patients.allPatients': 'सभी मरीज़',
     'patients.active': 'सक्रिय',
     'patients.critical': 'गंभीर',
     'patients.moreFilters': 'अधिक फिल्टर',
     'patients.noPatients': 'आपके मानदंडों से मेल खाने वाले कोई मरीज़ नहीं मिले।',
     'patients.noData': 'अभी तक कोई मरीज़ नहीं जोड़े गए। शुरू करने के लिए "मरीज़ जोड़ें" पर क्लिक करें।',
     'patients.addPatient': 'मरीज़ जोड़ें',
     'patients.priorityCases': 'प्राथमिकता मामले',
     'patients.patientDetails': 'मरीज़ विवरण',
     'patients.age': 'उम्र',
     'patients.condition': 'स्थिति',
     'patients.phone': 'फोन',
     'patients.address': 'पता',
     'patients.location': 'स्थान',
     'patients.status': 'स्थिति',
     'patients.lastVisit': 'अंतिम यात्रा',
     'patients.quickActions': 'त्वरित कार्य',
     'patients.patientInfo': 'मरीज़ जानकारी',
     'patients.years': 'वर्ष',
     'patients.notProvided': 'प्रदान नहीं किया गया',
     
     // Appointments
     'appointments.title': 'अपॉइंटमेंट',
     'appointments.subtitle': 'मरीज़ों की अपॉइंटमेंट शेड्यूल करें और प्रबंधित करें',
     'appointments.todaySchedule': 'आज का कार्यक्रम',
     'appointments.upcomingWeek': 'इस सप्ताह आगामी',
     'appointments.todaySummary': 'आज का सारांश',
     'appointments.totalAppointments': 'कुल अपॉइंटमेंट',
     'appointments.confirmed': 'पुष्ट',
     'appointments.pending': 'लंबित',
     'appointments.highPriority': 'उच्च प्राथमिकता',
     'appointments.patientName': 'मरीज़ का नाम',
     'appointments.type': 'प्रकार',
     'appointments.time': 'समय',
     'appointments.duration': 'अवधि',
     'appointments.doctor': 'डॉक्टर',
     'appointments.priority': 'प्राथमिकता',
     'appointments.appointmentDetails': 'अपॉइंटमेंट विवरण',
     'appointments.patientInfo': 'मरीज़ जानकारी',
     'appointments.editAppointment': 'अपॉइंटमेंट संपादित करें',
     'appointments.cancelAppointment': 'अपॉइंटमेंट रद्द करें',
     'appointments.day': 'दिन',
     'appointments.week': 'सप्ताह',
     'appointments.month': 'महीना',
     'appointments.filterByStatus': 'स्थिति के अनुसार फिल्टर करें',
     
     // Reports
     'reports.title': 'स्वास्थ्य रिपोर्ट',
     'reports.subtitle': 'जेनरेट किए गए स्वास्थ्य विश्लेषण और प्रदर्शन रिपोर्ट',
     'reports.totalGenerated': 'कुल जेनरेट की गई रिपोर्ट',
     'reports.maternalCoverage': 'मातृ स्वास्थ्य कवरेज',
     'reports.childVaccination': 'बाल टीकाकरण दर',
     'reports.dataQuality': 'डेटा गुणवत्ता स्कोर',
     'reports.thisMonth': 'इस महीने',
     'reports.fromTarget': 'लक्ष्य से',
     'reports.dataIntegrity': 'उत्कृष्ट डेटा अखंडता',
     'reports.allReports': 'सभी रिपोर्ट',
     'reports.maternalHealth': 'मातृ स्वास्थ्य',
     'reports.childHealth': 'बाल स्वास्थ्य',
     'reports.vaccination': 'टीकाकरण',
     'reports.period': 'अवधि',
     'reports.generated': 'जेनरेट किया गया',
     'reports.keyMetrics': 'मुख्य मेट्रिक्स',
     'reports.customReport': 'कस्टम रिपोर्ट चाहिए?',
     'reports.customReportDesc': 'हमारे उन्नत विश्लेषण इंजन के साथ अपनी आवश्यकताओं के आधार पर विशिष्ट रिपोर्ट जेनरेट करें।',
     'reports.createCustom': 'कस्टम रिपोर्ट बनाएं',
     'reports.reportDetails': 'रिपोर्ट विवरण',
     'reports.summary': 'सारांश',
     'reports.scheduleSuccess': 'रिपोर्ट शेड्यूल हो गई',
     'reports.scheduleDesc': 'आपकी रिपोर्ट साप्ताहिक जेनरेशन के लिए शेड्यूल हो गई है।',
     'reports.generateSuccess': 'रिपोर्ट सफलतापूर्वक जेनरेट हुई',
     'reports.generateDesc': 'आपकी स्वास्थ्य रिपोर्ट जेनरेट हो गई है और डाउनलोड के लिए तैयार है।',
     'reports.downloadStart': 'डाउनलोड शुरू हुआ',
     'reports.downloadDesc': 'डाउनलोड हो रहा है।',
     'reports.exportSuccess': 'निर्यात सफल',
     'reports.exportDesc': 'मरीज़ रिकॉर्ड सफलतापूर्वक निर्यात किए गए।',
     'reports.weekly': 'साप्ताहिक',
     'reports.monthly': 'मासिक',
     'reports.quarterly': 'त्रैमासिक',
     'reports.yearly': 'वार्षिक',
     'reports.completed': 'पूर्ण',
     'reports.processing': 'प्रसंस्करण',
     'reports.scheduleSimilar': 'समान रिपोर्ट शेड्यूल करें',
     
     // Critical Patients
     'critical.title': 'गंभीर मरीज़ अलर्ट',
     'critical.postpartumHypertension': 'प्रसवोत्तर उच्च रक्तचाप',
     'critical.highRiskPregnancy': 'उच्च जोखिम गर्भावस्था निगरानी',
     
     // Emergency
     'emergency.title': 'आपातकालीन अलर्ट सक्रिय',
     'emergency.description': 'आपातकालीन सेवाओं को सूचित कर दिया गया है और चिकित्सा सहायता भेजी जा रही है।',
     'emergency.eta': 'चिकित्सा टीम ETA: 10-15 मिनट',
     'emergency.contact': 'आपातकालीन संपर्क: +91 108',
     'emergency.reference': 'संदर्भ ID',
     'emergency.triggered': 'आपातकालीन अलर्ट सक्रिय',
     'emergency.response': 'आपातकालीन सेवाओं को सूचित कर दिया गया है। चिकित्सा टीम तुरंत जवाब देगी।',
     
     // Form Labels
     'form.name': 'नाम',
     'form.age': 'उम्र',
     'form.phone': 'फोन',
     'form.address': 'पता',
     'form.condition': 'स्थिति',
     'form.notes': 'नोट्स',
     
     // Footer
     'footer.mission': 'हमारा मिशन',
     'footer.missionText': 'कम सेवा वाले समुदायों में महिलाओं और बच्चों के लिए सुलभ, व्यापक स्वास्थ्य निगरानी प्रदान करना।',
     'footer.copyright': '© 2025 SheCure. बेहतर स्वास्थ्य सेवा के लिए ❤️ के साथ बनाया गया।',
     'footer.tagline': 'सुलभ स्वास्थ्य देखभाल के माध्यम से महिलाओं और बच्चों को सशक्त बनाना',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};