// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvjwhbzlbcvwnipsthmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2andoYnpsYmN2d25pcHN0aG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjcwNjcsImV4cCI6MjA2OTcwMzA2N30.VWkWMAvTEqGxhFz0h_SPPqDOlDTtu2h1Fq02JZtOq5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});